//! Excel's built-in function numbers, as BIFF8 formulas refer to them.
//!
//! A formula token names a function by index, not by name. The table below is
//! the one the format has carried since Excel 97; its numbers, argument counts
//! and operand classes were taken from the `xlrd` Python package and checked
//! against `xlwt`, two independent implementations. They disagree in three
//! places, and each is settled by Excel's own signature: the lower bound of a
//! few variadic functions (`xlrd` allows none, Excel requires one), and
//! `GETPIVOTDATA` and `RTD`, which take up to 30 arguments where `xlrd` stops
//! at 2 and 5. The upper bound matters: a formula over it is not written.
//!
//! Functions added after Excel 2003 have no number: a file stores them by
//! name, as the analysis add-in functions ([`ADD_IN`]) always were.

/// One built-in function.
#[derive(Debug, Clone, Copy)]
pub struct Function {
    /// The number a formula token uses.
    pub index: u16,
    /// The name, as a formula writes it.
    pub name: &'static str,
    /// Fewest arguments.
    pub min: u8,
    /// Most arguments.
    pub max: u8,
    /// What the function returns: `V` a value, `R` a reference, `A` an array.
    pub returns: u8,
    /// The class each argument is expected in, the last repeating for the
    /// rest.
    pub args: &'static str,
}

impl Function {
    /// The class the argument at a position is expected in.
    #[must_use]
    pub fn arg_class(&self, position: usize) -> u8 {
        let bytes = self.args.as_bytes();
        bytes
            .get(position)
            .or_else(|| bytes.last())
            .copied()
            .unwrap_or(b'V')
    }

    /// Whether a formula stores this function with its argument count, which
    /// is every function whose count may vary.
    #[must_use]
    pub const fn is_variadic(&self) -> bool {
        self.min != self.max
    }
}

/// Every numbered function, in index order.
pub const FUNCTIONS: &[Function] = &[
    Function {
        index: 0,
        name: "COUNT",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 1,
        name: "IF",
        min: 2,
        max: 3,
        returns: b'V',
        args: "VRR",
    },
    Function {
        index: 2,
        name: "ISNA",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 3,
        name: "ISERROR",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 4,
        name: "SUM",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 5,
        name: "AVERAGE",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 6,
        name: "MIN",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 7,
        name: "MAX",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 8,
        name: "ROW",
        min: 0,
        max: 1,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 9,
        name: "COLUMN",
        min: 0,
        max: 1,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 10,
        name: "NA",
        min: 0,
        max: 0,
        returns: b'V',
        args: "",
    },
    Function {
        index: 11,
        name: "NPV",
        min: 2,
        max: 30,
        returns: b'V',
        args: "VR",
    },
    Function {
        index: 12,
        name: "STDEV",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 13,
        name: "DOLLAR",
        min: 1,
        max: 2,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 14,
        name: "FIXED",
        min: 2,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 15,
        name: "SIN",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 16,
        name: "COS",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 17,
        name: "TAN",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 18,
        name: "ATAN",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 19,
        name: "PI",
        min: 0,
        max: 0,
        returns: b'V',
        args: "",
    },
    Function {
        index: 20,
        name: "SQRT",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 21,
        name: "EXP",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 22,
        name: "LN",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 23,
        name: "LOG10",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 24,
        name: "ABS",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 25,
        name: "INT",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 26,
        name: "SIGN",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 27,
        name: "ROUND",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 28,
        name: "LOOKUP",
        min: 2,
        max: 3,
        returns: b'V',
        args: "VR",
    },
    Function {
        index: 29,
        name: "INDEX",
        min: 2,
        max: 4,
        returns: b'R',
        args: "RVVV",
    },
    Function {
        index: 30,
        name: "REPT",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 31,
        name: "MID",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 32,
        name: "LEN",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 33,
        name: "VALUE",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 34,
        name: "TRUE",
        min: 0,
        max: 0,
        returns: b'V',
        args: "",
    },
    Function {
        index: 35,
        name: "FALSE",
        min: 0,
        max: 0,
        returns: b'V',
        args: "",
    },
    Function {
        index: 36,
        name: "AND",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 37,
        name: "OR",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 38,
        name: "NOT",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 39,
        name: "MOD",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 40,
        name: "DCOUNT",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RRR",
    },
    Function {
        index: 41,
        name: "DSUM",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RRR",
    },
    Function {
        index: 42,
        name: "DAVERAGE",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RRR",
    },
    Function {
        index: 43,
        name: "DMIN",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RRR",
    },
    Function {
        index: 44,
        name: "DMAX",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RRR",
    },
    Function {
        index: 45,
        name: "DSTDEV",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RRR",
    },
    Function {
        index: 46,
        name: "VAR",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 47,
        name: "DVAR",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RRR",
    },
    Function {
        index: 48,
        name: "TEXT",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 49,
        name: "LINEST",
        min: 1,
        max: 4,
        returns: b'A',
        args: "RRVV",
    },
    Function {
        index: 50,
        name: "TREND",
        min: 1,
        max: 4,
        returns: b'A',
        args: "RRRV",
    },
    Function {
        index: 51,
        name: "LOGEST",
        min: 1,
        max: 4,
        returns: b'A',
        args: "RRVV",
    },
    Function {
        index: 52,
        name: "GROWTH",
        min: 1,
        max: 4,
        returns: b'A',
        args: "RRRV",
    },
    Function {
        index: 56,
        name: "PV",
        min: 3,
        max: 5,
        returns: b'V',
        args: "VVVVV",
    },
    Function {
        index: 57,
        name: "FV",
        min: 3,
        max: 5,
        returns: b'V',
        args: "VVVVV",
    },
    Function {
        index: 58,
        name: "NPER",
        min: 3,
        max: 5,
        returns: b'V',
        args: "VVVVV",
    },
    Function {
        index: 59,
        name: "PMT",
        min: 3,
        max: 5,
        returns: b'V',
        args: "VVVVV",
    },
    Function {
        index: 60,
        name: "RATE",
        min: 3,
        max: 6,
        returns: b'V',
        args: "VVVVVV",
    },
    Function {
        index: 61,
        name: "MIRR",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RVV",
    },
    Function {
        index: 62,
        name: "IRR",
        min: 1,
        max: 2,
        returns: b'V',
        args: "RV",
    },
    Function {
        index: 63,
        name: "RAND",
        min: 0,
        max: 0,
        returns: b'V',
        args: "",
    },
    Function {
        index: 64,
        name: "MATCH",
        min: 2,
        max: 3,
        returns: b'V',
        args: "VRR",
    },
    Function {
        index: 65,
        name: "DATE",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 66,
        name: "TIME",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 67,
        name: "DAY",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 68,
        name: "MONTH",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 69,
        name: "YEAR",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 70,
        name: "WEEKDAY",
        min: 1,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 71,
        name: "HOUR",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 72,
        name: "MINUTE",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 73,
        name: "SECOND",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 74,
        name: "NOW",
        min: 0,
        max: 0,
        returns: b'V',
        args: "",
    },
    Function {
        index: 75,
        name: "AREAS",
        min: 1,
        max: 1,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 76,
        name: "ROWS",
        min: 1,
        max: 1,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 77,
        name: "COLUMNS",
        min: 1,
        max: 1,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 78,
        name: "OFFSET",
        min: 3,
        max: 5,
        returns: b'R',
        args: "RVVVV",
    },
    Function {
        index: 82,
        name: "SEARCH",
        min: 2,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 83,
        name: "TRANSPOSE",
        min: 1,
        max: 1,
        returns: b'A',
        args: "A",
    },
    Function {
        index: 86,
        name: "TYPE",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 92,
        name: "SERIESSUM",
        min: 4,
        max: 4,
        returns: b'V',
        args: "VVVA",
    },
    Function {
        index: 97,
        name: "ATAN2",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 98,
        name: "ASIN",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 99,
        name: "ACOS",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 100,
        name: "CHOOSE",
        min: 2,
        max: 30,
        returns: b'V',
        args: "VR",
    },
    Function {
        index: 101,
        name: "HLOOKUP",
        min: 3,
        max: 4,
        returns: b'V',
        args: "VRRV",
    },
    Function {
        index: 102,
        name: "VLOOKUP",
        min: 3,
        max: 4,
        returns: b'V',
        args: "VRRV",
    },
    Function {
        index: 105,
        name: "ISREF",
        min: 1,
        max: 1,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 109,
        name: "LOG",
        min: 1,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 111,
        name: "CHAR",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 112,
        name: "LOWER",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 113,
        name: "UPPER",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 114,
        name: "PROPER",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 115,
        name: "LEFT",
        min: 1,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 116,
        name: "RIGHT",
        min: 1,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 117,
        name: "EXACT",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 118,
        name: "TRIM",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 119,
        name: "REPLACE",
        min: 4,
        max: 4,
        returns: b'V',
        args: "VVVV",
    },
    Function {
        index: 120,
        name: "SUBSTITUTE",
        min: 3,
        max: 4,
        returns: b'V',
        args: "VVVV",
    },
    Function {
        index: 121,
        name: "CODE",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 124,
        name: "FIND",
        min: 2,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 125,
        name: "CELL",
        min: 1,
        max: 2,
        returns: b'V',
        args: "VR",
    },
    Function {
        index: 126,
        name: "ISERR",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 127,
        name: "ISTEXT",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 128,
        name: "ISNUMBER",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 129,
        name: "ISBLANK",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 130,
        name: "T",
        min: 1,
        max: 1,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 131,
        name: "N",
        min: 1,
        max: 1,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 140,
        name: "DATEVALUE",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 141,
        name: "TIMEVALUE",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 142,
        name: "SLN",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 143,
        name: "SYD",
        min: 4,
        max: 4,
        returns: b'V',
        args: "VVVV",
    },
    Function {
        index: 144,
        name: "DDB",
        min: 4,
        max: 5,
        returns: b'V',
        args: "VVVVV",
    },
    Function {
        index: 148,
        name: "INDIRECT",
        min: 1,
        max: 2,
        returns: b'R',
        args: "VV",
    },
    Function {
        index: 162,
        name: "CLEAN",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 163,
        name: "MDETERM",
        min: 1,
        max: 1,
        returns: b'V',
        args: "A",
    },
    Function {
        index: 164,
        name: "MINVERSE",
        min: 1,
        max: 1,
        returns: b'A',
        args: "A",
    },
    Function {
        index: 165,
        name: "MMULT",
        min: 2,
        max: 2,
        returns: b'A',
        args: "AA",
    },
    Function {
        index: 167,
        name: "IPMT",
        min: 4,
        max: 6,
        returns: b'V',
        args: "VVVVVV",
    },
    Function {
        index: 168,
        name: "PPMT",
        min: 4,
        max: 6,
        returns: b'V',
        args: "VVVVVV",
    },
    Function {
        index: 169,
        name: "COUNTA",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 183,
        name: "PRODUCT",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 184,
        name: "FACT",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 189,
        name: "DPRODUCT",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RRR",
    },
    Function {
        index: 190,
        name: "ISNONTEXT",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 193,
        name: "STDEVP",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 194,
        name: "VARP",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 195,
        name: "DSTDEVP",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RRR",
    },
    Function {
        index: 196,
        name: "DVARP",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RRR",
    },
    Function {
        index: 197,
        name: "TRUNC",
        min: 1,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 198,
        name: "ISLOGICAL",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 199,
        name: "DCOUNTA",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RRR",
    },
    Function {
        index: 204,
        name: "USDOLLAR",
        min: 1,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 205,
        name: "FINDB",
        min: 2,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 206,
        name: "SEARCHB",
        min: 2,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 207,
        name: "REPLACEB",
        min: 4,
        max: 4,
        returns: b'V',
        args: "VVVV",
    },
    Function {
        index: 208,
        name: "LEFTB",
        min: 1,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 209,
        name: "RIGHTB",
        min: 1,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 210,
        name: "MIDB",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 211,
        name: "LENB",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 212,
        name: "ROUNDUP",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 213,
        name: "ROUNDDOWN",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 214,
        name: "ASC",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 215,
        name: "DBCS",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 216,
        name: "RANK",
        min: 2,
        max: 3,
        returns: b'V',
        args: "VRV",
    },
    Function {
        index: 219,
        name: "ADDRESS",
        min: 2,
        max: 5,
        returns: b'V',
        args: "VVVVV",
    },
    Function {
        index: 220,
        name: "DAYS360",
        min: 2,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 221,
        name: "TODAY",
        min: 0,
        max: 0,
        returns: b'V',
        args: "",
    },
    Function {
        index: 222,
        name: "VDB",
        min: 5,
        max: 7,
        returns: b'V',
        args: "VVVVVVV",
    },
    Function {
        index: 227,
        name: "MEDIAN",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 228,
        name: "SUMPRODUCT",
        min: 1,
        max: 30,
        returns: b'V',
        args: "A",
    },
    Function {
        index: 229,
        name: "SINH",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 230,
        name: "COSH",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 231,
        name: "TANH",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 232,
        name: "ASINH",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 233,
        name: "ACOSH",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 234,
        name: "ATANH",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 235,
        name: "DGET",
        min: 3,
        max: 3,
        returns: b'V',
        args: "RRR",
    },
    Function {
        index: 244,
        name: "INFO",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 247,
        name: "DB",
        min: 4,
        max: 5,
        returns: b'V',
        args: "VVVVV",
    },
    Function {
        index: 252,
        name: "FREQUENCY",
        min: 2,
        max: 2,
        returns: b'A',
        args: "RR",
    },
    Function {
        index: 261,
        name: "ERROR.TYPE",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 269,
        name: "AVEDEV",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 270,
        name: "BETADIST",
        min: 3,
        max: 5,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 271,
        name: "GAMMALN",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 272,
        name: "BETAINV",
        min: 3,
        max: 5,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 273,
        name: "BINOMDIST",
        min: 4,
        max: 4,
        returns: b'V',
        args: "VVVV",
    },
    Function {
        index: 274,
        name: "CHIDIST",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 275,
        name: "CHIINV",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 276,
        name: "COMBIN",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 277,
        name: "CONFIDENCE",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 278,
        name: "CRITBINOM",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 279,
        name: "EVEN",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 280,
        name: "EXPONDIST",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 281,
        name: "FDIST",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 282,
        name: "FINV",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 283,
        name: "FISHER",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 284,
        name: "FISHERINV",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 285,
        name: "FLOOR",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 286,
        name: "GAMMADIST",
        min: 4,
        max: 4,
        returns: b'V',
        args: "VVVV",
    },
    Function {
        index: 287,
        name: "GAMMAINV",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 288,
        name: "CEILING",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 289,
        name: "HYPGEOMDIST",
        min: 4,
        max: 4,
        returns: b'V',
        args: "VVVV",
    },
    Function {
        index: 290,
        name: "LOGNORMDIST",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 291,
        name: "LOGINV",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 292,
        name: "NEGBINOMDIST",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 293,
        name: "NORMDIST",
        min: 4,
        max: 4,
        returns: b'V',
        args: "VVVV",
    },
    Function {
        index: 294,
        name: "NORMSDIST",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 295,
        name: "NORMINV",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 296,
        name: "NORMSINV",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 297,
        name: "STANDARDIZE",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 298,
        name: "ODD",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 299,
        name: "PERMUT",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 300,
        name: "POISSON",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 301,
        name: "TDIST",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 302,
        name: "WEIBULL",
        min: 4,
        max: 4,
        returns: b'V',
        args: "VVVV",
    },
    Function {
        index: 303,
        name: "SUMXMY2",
        min: 2,
        max: 2,
        returns: b'V',
        args: "AA",
    },
    Function {
        index: 304,
        name: "SUMX2MY2",
        min: 2,
        max: 2,
        returns: b'V',
        args: "AA",
    },
    Function {
        index: 305,
        name: "SUMX2PY2",
        min: 2,
        max: 2,
        returns: b'V',
        args: "AA",
    },
    Function {
        index: 306,
        name: "CHITEST",
        min: 2,
        max: 2,
        returns: b'V',
        args: "AA",
    },
    Function {
        index: 307,
        name: "CORREL",
        min: 2,
        max: 2,
        returns: b'V',
        args: "AA",
    },
    Function {
        index: 308,
        name: "COVAR",
        min: 2,
        max: 2,
        returns: b'V',
        args: "AA",
    },
    Function {
        index: 309,
        name: "FORECAST",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VAA",
    },
    Function {
        index: 310,
        name: "FTEST",
        min: 2,
        max: 2,
        returns: b'V',
        args: "AA",
    },
    Function {
        index: 311,
        name: "INTERCEPT",
        min: 2,
        max: 2,
        returns: b'V',
        args: "AA",
    },
    Function {
        index: 312,
        name: "PEARSON",
        min: 2,
        max: 2,
        returns: b'V',
        args: "AA",
    },
    Function {
        index: 313,
        name: "RSQ",
        min: 2,
        max: 2,
        returns: b'V',
        args: "AA",
    },
    Function {
        index: 314,
        name: "STEYX",
        min: 2,
        max: 2,
        returns: b'V',
        args: "AA",
    },
    Function {
        index: 315,
        name: "SLOPE",
        min: 2,
        max: 2,
        returns: b'V',
        args: "AA",
    },
    Function {
        index: 316,
        name: "TTEST",
        min: 4,
        max: 4,
        returns: b'V',
        args: "AAVV",
    },
    Function {
        index: 317,
        name: "PROB",
        min: 3,
        max: 4,
        returns: b'V',
        args: "AAV",
    },
    Function {
        index: 318,
        name: "DEVSQ",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 319,
        name: "GEOMEAN",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 320,
        name: "HARMEAN",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 321,
        name: "SUMSQ",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 322,
        name: "KURT",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 323,
        name: "SKEW",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 324,
        name: "ZTEST",
        min: 2,
        max: 3,
        returns: b'V',
        args: "RV",
    },
    Function {
        index: 325,
        name: "LARGE",
        min: 2,
        max: 2,
        returns: b'V',
        args: "RV",
    },
    Function {
        index: 326,
        name: "SMALL",
        min: 2,
        max: 2,
        returns: b'V',
        args: "RV",
    },
    Function {
        index: 327,
        name: "QUARTILE",
        min: 2,
        max: 2,
        returns: b'V',
        args: "RV",
    },
    Function {
        index: 328,
        name: "PERCENTILE",
        min: 2,
        max: 2,
        returns: b'V',
        args: "RV",
    },
    Function {
        index: 329,
        name: "PERCENTRANK",
        min: 2,
        max: 3,
        returns: b'V',
        args: "RV",
    },
    Function {
        index: 330,
        name: "MODE",
        min: 1,
        max: 30,
        returns: b'V',
        args: "A",
    },
    Function {
        index: 331,
        name: "TRIMMEAN",
        min: 2,
        max: 2,
        returns: b'V',
        args: "RV",
    },
    Function {
        index: 332,
        name: "TINV",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 336,
        name: "CONCATENATE",
        min: 1,
        max: 30,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 337,
        name: "POWER",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 342,
        name: "RADIANS",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 343,
        name: "DEGREES",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 344,
        name: "SUBTOTAL",
        min: 2,
        max: 30,
        returns: b'V',
        args: "VR",
    },
    Function {
        index: 345,
        name: "SUMIF",
        min: 2,
        max: 3,
        returns: b'V',
        args: "RVR",
    },
    Function {
        index: 346,
        name: "COUNTIF",
        min: 2,
        max: 2,
        returns: b'V',
        args: "RV",
    },
    Function {
        index: 347,
        name: "COUNTBLANK",
        min: 1,
        max: 1,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 350,
        name: "ISPMT",
        min: 4,
        max: 4,
        returns: b'V',
        args: "VVVV",
    },
    Function {
        index: 351,
        name: "DATEDIF",
        min: 3,
        max: 3,
        returns: b'V',
        args: "VVV",
    },
    Function {
        index: 352,
        name: "DATESTRING",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 353,
        name: "NUMBERSTRING",
        min: 2,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 354,
        name: "ROMAN",
        min: 1,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 358,
        name: "GETPIVOTDATA",
        min: 2,
        max: 30,
        returns: b'V',
        args: "RV",
    },
    Function {
        index: 359,
        name: "HYPERLINK",
        min: 1,
        max: 2,
        returns: b'V',
        args: "VV",
    },
    Function {
        index: 360,
        name: "PHONETIC",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 361,
        name: "AVERAGEA",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 362,
        name: "MAXA",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 363,
        name: "MINA",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 364,
        name: "STDEVPA",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 365,
        name: "VARPA",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 366,
        name: "STDEVA",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 367,
        name: "VARA",
        min: 1,
        max: 30,
        returns: b'V',
        args: "R",
    },
    Function {
        index: 368,
        name: "BAHTTEXT",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 369,
        name: "THAIDAYOFWEEK",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 370,
        name: "THAIDIGIT",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 371,
        name: "THAIMONTHOFYEAR",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 372,
        name: "THAINUMSOUND",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 373,
        name: "THAINUMSTRING",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 374,
        name: "THAISTRINGLENGTH",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 375,
        name: "ISTHAIDIGIT",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 376,
        name: "ROUNDBAHTDOWN",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 377,
        name: "ROUNDBAHTUP",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 378,
        name: "THAIYEAR",
        min: 1,
        max: 1,
        returns: b'V',
        args: "V",
    },
    Function {
        index: 379,
        name: "RTD",
        min: 3,
        max: 30,
        returns: b'V',
        args: "V",
    },
];

/// Functions that came from the Analysis `ToolPak` add-in and are stored by
/// name, without the `_xlfn.` prefix later additions carry.
pub const ADD_IN: &[&str] = &[
    "ACCRINT",
    "ACCRINTM",
    "AMORDEGRC",
    "AMORLINC",
    "BESSELI",
    "BESSELJ",
    "BESSELK",
    "BESSELY",
    "BIN2DEC",
    "BIN2HEX",
    "BIN2OCT",
    "COMPLEX",
    "CONVERT",
    "COUPDAYBS",
    "COUPDAYS",
    "COUPDAYSNC",
    "COUPNCD",
    "COUPNUM",
    "COUPPCD",
    "CUMIPMT",
    "CUMPRINC",
    "DEC2BIN",
    "DEC2HEX",
    "DEC2OCT",
    "DELTA",
    "DISC",
    "DOLLARDE",
    "DOLLARFR",
    "DURATION",
    "EDATE",
    "EFFECT",
    "EOMONTH",
    "ERF",
    "ERFC",
    "FACTDOUBLE",
    "FVSCHEDULE",
    "GCD",
    "GESTEP",
    "HEX2BIN",
    "HEX2DEC",
    "HEX2OCT",
    "IMABS",
    "IMAGINARY",
    "IMARGUMENT",
    "IMCONJUGATE",
    "IMCOS",
    "IMDIV",
    "IMEXP",
    "IMLN",
    "IMLOG10",
    "IMLOG2",
    "IMPOWER",
    "IMPRODUCT",
    "IMREAL",
    "IMSIN",
    "IMSQRT",
    "IMSUB",
    "IMSUM",
    "INTRATE",
    "ISEVEN",
    "ISODD",
    "LCM",
    "MDURATION",
    "MROUND",
    "MULTINOMIAL",
    "NETWORKDAYS",
    "NOMINAL",
    "OCT2BIN",
    "OCT2DEC",
    "OCT2HEX",
    "ODDFPRICE",
    "ODDFYIELD",
    "ODDLPRICE",
    "ODDLYIELD",
    "PRICE",
    "PRICEDISC",
    "PRICEMAT",
    "QUOTIENT",
    "RANDBETWEEN",
    "RECEIVED",
    "SERIESSUM",
    "SQRTPI",
    "TBILLEQ",
    "TBILLPRICE",
    "TBILLYIELD",
    "WEEKNUM",
    "WORKDAY",
    "XIRR",
    "XNPV",
    "YEARFRAC",
    "YIELD",
    "YIELDDISC",
    "YIELDMAT",
];

/// The function a token number names.
#[must_use]
pub fn by_index(index: u16) -> Option<&'static Function> {
    FUNCTIONS
        .binary_search_by_key(&index, |f| f.index)
        .ok()
        .and_then(|at| FUNCTIONS.get(at))
}

/// The functions numbered past the BIFF8 table.
///
/// Excel 2007 gave a number to the analysis add-in functions, which older
/// files reached by name, and to the handful it added itself
/// (`IFERROR`, `COUNTIFS`, `AVERAGEIF`); xlsb formulas use those numbers. The
/// pairs come from `SheetJS`, an independent implementation, and the ones this
/// crate has seen in a workbook written by Excel are checked against the same
/// workbook saved as xlsx, where the function stands written by name.
///
/// The count is how many arguments the function takes when it is written as
/// the fixed-argument token; `None` means only the counted token was seen for
/// it, and the fixed form of such a function is left unread rather than
/// guessed at.
static EXTENDED: &[(u16, &str, Option<u8>)] = &[
    (380, "CUBEVALUE", None),
    (381, "CUBEMEMBER", None),
    (382, "CUBEMEMBERPROPERTY", Some(3)),
    (383, "CUBERANKEDMEMBER", None),
    (384, "HEX2BIN", None),
    (385, "HEX2DEC", Some(1)),
    (386, "HEX2OCT", None),
    (387, "DEC2BIN", None),
    (388, "DEC2HEX", None),
    (389, "DEC2OCT", None),
    (390, "OCT2BIN", None),
    (391, "OCT2HEX", None),
    (392, "OCT2DEC", Some(1)),
    (393, "BIN2DEC", Some(1)),
    (394, "BIN2OCT", None),
    (395, "BIN2HEX", None),
    (396, "IMSUB", Some(2)),
    (397, "IMDIV", Some(2)),
    (398, "IMPOWER", Some(2)),
    (399, "IMABS", Some(1)),
    (400, "IMSQRT", Some(1)),
    (401, "IMLN", Some(1)),
    (402, "IMLOG2", Some(1)),
    (403, "IMLOG10", Some(1)),
    (404, "IMSIN", Some(1)),
    (405, "IMCOS", Some(1)),
    (406, "IMEXP", Some(1)),
    (407, "IMARGUMENT", Some(1)),
    (408, "IMCONJUGATE", Some(1)),
    (409, "IMAGINARY", Some(1)),
    (410, "IMREAL", Some(1)),
    (411, "COMPLEX", None),
    (412, "IMSUM", None),
    (413, "IMPRODUCT", None),
    (414, "SERIESSUM", Some(4)),
    (415, "FACTDOUBLE", Some(1)),
    (416, "SQRTPI", Some(1)),
    (417, "QUOTIENT", Some(2)),
    (418, "DELTA", None),
    (419, "GESTEP", None),
    (420, "ISEVEN", Some(1)),
    (421, "ISODD", Some(1)),
    (422, "MROUND", Some(2)),
    (423, "ERF", None),
    (424, "ERFC", Some(1)),
    (425, "BESSELJ", Some(2)),
    (426, "BESSELK", Some(2)),
    (427, "BESSELY", Some(2)),
    (428, "BESSELI", Some(2)),
    (429, "XIRR", None),
    (430, "XNPV", Some(3)),
    (431, "PRICEMAT", None),
    (432, "YIELDMAT", None),
    (433, "INTRATE", None),
    (434, "RECEIVED", None),
    (435, "DISC", None),
    (436, "PRICEDISC", None),
    (437, "YIELDDISC", None),
    (438, "TBILLEQ", Some(3)),
    (439, "TBILLPRICE", Some(3)),
    (440, "TBILLYIELD", Some(3)),
    (441, "PRICE", None),
    (442, "YIELD", None),
    (443, "DOLLARDE", Some(2)),
    (444, "DOLLARFR", Some(2)),
    (445, "NOMINAL", Some(2)),
    (446, "EFFECT", Some(2)),
    (447, "CUMPRINC", Some(6)),
    (448, "CUMIPMT", Some(6)),
    (449, "EDATE", Some(2)),
    (450, "EOMONTH", Some(2)),
    (451, "YEARFRAC", None),
    (452, "COUPDAYBS", None),
    (453, "COUPDAYS", None),
    (454, "COUPDAYSNC", None),
    (455, "COUPNCD", None),
    (456, "COUPNUM", None),
    (457, "COUPPCD", None),
    (458, "DURATION", None),
    (459, "MDURATION", None),
    (460, "ODDLPRICE", None),
    (461, "ODDLYIELD", None),
    (462, "ODDFPRICE", None),
    (463, "ODDFYIELD", None),
    (464, "RANDBETWEEN", Some(2)),
    (465, "WEEKNUM", None),
    (466, "AMORDEGRC", None),
    (467, "AMORLINC", None),
    (468, "CONVERT", Some(3)),
    (469, "ACCRINT", None),
    (470, "ACCRINTM", None),
    (471, "WORKDAY", None),
    (472, "NETWORKDAYS", None),
    (473, "GCD", None),
    (474, "MULTINOMIAL", None),
    (475, "LCM", None),
    (476, "FVSCHEDULE", Some(2)),
    (477, "CUBEKPIMEMBER", None),
    (478, "CUBESET", None),
    (479, "CUBESETCOUNT", Some(1)),
    (480, "IFERROR", Some(2)),
    (481, "COUNTIFS", None),
    (482, "SUMIFS", None),
    (483, "AVERAGEIF", None),
    (484, "AVERAGEIFS", None),
];

/// The name and fixed argument count of a function numbered past the BIFF8
/// table. Only formula text uses these: evaluation knows these functions by
/// name, and their argument classes are not in the table.
#[must_use]
pub fn extended(index: u16) -> Option<(&'static str, Option<u8>)> {
    EXTENDED
        .binary_search_by_key(&index, |(number, _, _)| *number)
        .ok()
        .map(|at| (EXTENDED[at].1, EXTENDED[at].2))
}

/// The numbered function a name stands for, ignoring case.
///
/// Asked on every function call the engine makes, so the table is indexed
/// once rather than walked.
#[must_use]
pub fn by_name(name: &str) -> Option<&'static Function> {
    static INDEX: std::sync::OnceLock<std::collections::HashMap<&'static str, &'static Function>> =
        std::sync::OnceLock::new();
    let index = INDEX.get_or_init(|| FUNCTIONS.iter().map(|f| (f.name, f)).collect());
    match index.get(name) {
        Some(f) => Some(f),
        None if name.bytes().any(|b| b.is_ascii_lowercase()) => {
            index.get(name.to_ascii_uppercase().as_str()).copied()
        }
        None => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_sorted_and_names_are_unique() {
        assert!(FUNCTIONS.windows(2).all(|w| w[0].index < w[1].index));
        assert_eq!(by_index(4).map(|f| f.name), Some("SUM"));
        assert_eq!(by_name("vlookup").map(|f| f.index), Some(102));
        for f in FUNCTIONS {
            assert_eq!(
                by_name(f.name).map(|g| g.index),
                Some(f.index),
                "{}",
                f.name
            );
        }
    }

    #[test]
    fn the_extended_table_is_sorted_and_starts_past_the_first() {
        assert!(EXTENDED.windows(2).all(|w| w[0].0 < w[1].0));
        let first = EXTENDED.first().expect("the table has entries").0;
        assert!(
            FUNCTIONS.iter().all(|f| f.index < first),
            "the two tables must not claim the same number"
        );
        assert_eq!(extended(483).map(|(name, _)| name), Some("AVERAGEIF"));
        assert_eq!(extended(449), Some(("EDATE", Some(2))));
        assert_eq!(extended(1), None, "numbers of the first table are not here");
    }

    /// The names come from another implementation's table, so a typo or a
    /// number off by one would show up as a formula naming a function nobody
    /// has ever heard of. Everything here should be a function this engine
    /// knows, bar the handful that need a world outside the workbook.
    #[cfg(feature = "formulas")]
    #[test]
    fn every_extended_name_is_a_function_this_crate_knows() {
        const OUTSIDE: &[&str] = &[
            "CUBEVALUE",
            "CUBEMEMBER",
            "CUBEMEMBERPROPERTY",
            "CUBERANKEDMEMBER",
            "CUBESET",
            "CUBESETCOUNT",
            "CUBEKPIMEMBER",
        ];
        for &(index, name, _) in EXTENDED {
            assert!(
                crate::formula::functions::is_known(name) || OUTSIDE.contains(&name),
                "{index} names {name:?}, which this crate has never heard of"
            );
        }
    }
}
